management:
  check-token: false
  allowed-ips:
    - "127.0.0.1"
    - "localhost"
    - "0:0:0:0:0:0:0:1"
#    - "*"
quarkus:
  application:
    name: MuYunGateway
  config:
    locations: /Users/aruis/develop/workspace-github/MuYunGateway/src/main/resources/config/gateway-config.yml
  http:
    port: 8888
    enable-compression: true
    non-application-root-path: /gw
  rest:
    path: /gw/api
  banner:
    path: banner.txt
  log:
    level: INFO
    console:
      enable: true
      format: "%d{yyyy-MM-dd HH:mm:ss} %-5p [%c{3.}] (%t) %s%e%n"

"%prod":
  quarkus:
    log:
      file:
        enable: true
        path: logs/muyun-gateway.log
        level: WARN
        format: "%d{yyyy-MM-dd HH:mm:ss} %-5p [%c{3.}] (%t) %s%e%n"
        rotation:
          file-suffix: .yyyy-MM-dd
          rotate-on-boot: true
          max-backup-index: 7
